version: '3'
services:
  jupyterlab:
    container_name: 'jupyterlab'
    image: jupyterlab
    build:
      context: .
      dockerfile: "Dockerfile"
    user: root
    volumes:
      - jupyterlab-dir:/home/JupyterLab/codes
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      TZ: Asia/Tokyo
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.notebook_dir='/home/JupyterLab/codes' --NotebookApp.token='${JUPYTERLAB_MY_TOKEN}'
volumes:
  jupyterlab-dir:
    driver_opts:
      type: none
      device: /home/greenpepper/miscs/jupyterlab/codes
      o: bind
